[package]
name = "package-scanner"
version.workspace = true
edition.workspace = true

[dependencies]
adb-bridge = { path = "../adb-bridge" }
serde = { workspace = true }
thiserror = { workspace = true }
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls"] }
axmldecoder = "0.5.0"
base64 = { workspace = true }
rayon = "1.10"
